### ISSUE TITLE
undefined function __decorations__/0

### ISSUE THREAD

**Issue by hanzejl** [acutario/decoratex#4]
if I add "use Decoratex" to web.ex, those models doesn't have define function "decorators" raise "CompileError, undefined function __decorations__/0"

**Comment by rsierra** [comment]
Thx! I will take a look, meanwhile you can add `use Decoratex` in each file needed instead.

**Comment by rsierra** [comment]
It is fixed in 0af4ff3dbb42855d640578f87292358d69beaa5c.

I will release a minor version in the next days.

**Comment by rsierra** [comment]
Solved in #8
